### ISSUE TITLE
Include proper documentation

### ISSUE THREAD

**Issue by RobPasMue** [pyansys/pyansys-tools-versioning#9]
### 📝 Description of the feature

Following other PyAnsys projects, we should include some proper docs:
* Getting started section
* User guide
* API section
* ...

### 💡 Steps for implementing the feature

-

### 🔗 Useful links and references

-

**Comment by jorgepiloto** [comment]
Working on this 💪🏽

**Comment by RobPasMue** [comment]
Thanks @jorgepiloto!
